# -*- coding: utf-8 -*-
"""arguments_scopes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rFezieqPUuQxcx_PHypT0waY3fA04CeG
"""

def argument_printer(arg_position1, arg_position2):
   print('Argument at position 1:', arg_position1)
   print('Argument at position 2:', arg_position2)

argument_printer('value 1', 'value 2')

def greetings(first_name, last_name, auto_correction):
  if auto_correction == True:
    capitalized_first_name = first_name.capitalize()
    capitalized_last_name = last_name.capitalize() 
    print("Hello,", capitalized_first_name, capitalized_last_name) 
  else: 
    print("Hello,", first_name, last_name)

greetings('jOE', 'smiTH', True)

greetings('jOE', 'smiTH', False)

def greetings(first_name, last_name, auto_correction = True):
  if auto_correction == True: 
    capitalized_first_name = first_name.capitalize()
    capitalized_last_name = last_name.capitalize() 
    print("Hello,", capitalized_first_name, capitalized_last_name) 
  else: 
    print("Hello,", first_name, last_name)

greetings('jOE', 'smiTH')

def car(brand, model, colour):
    print('My favourite car is the', brand, model, 'in the colour', colour)

car('Audi', 'R8', 'black')

car(colour = 'black', model = 'R8', brand = 'Audi')

number = 13 #Global Variable
 
def change_number():
 number = 4 #Local Variable
 
change_number()
print(number)

number = 13
 
def change_number():
 global number 
 number = 4
 
change_number()
print(number)