# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XsAbLIQGz9peLhoMHaWer3SJ1jXcfi3J
"""

number = '15'
print('Type of number before int() function: ', type(number))
 
number = int(number)
 
print('Type of number after int() function: ', type(number))

def hello(name):
  print('Hello', name)

hello('Joe')

def sum(number1, number2):
  print(number1 + number2)

sum(3, 5)

result = sum(3, 5)
print(result)

def sum(number1, number2):
  answer = number1 + number2
  return answer
 
result = sum(3, 5)
print(result)