# -*- coding: utf-8 -*-
"""modules.ipynb

Automatically generated by Colaboratory.


import test

test.greetings('Joe')

!pip install seaborn

import seaborn as sns

import seaborn as sns
 
data = [1, 2, 10, 3, 5, 6, 13]

sns.lineplot(x=range(7),y=data)