# -*- coding: utf-8 -*-
"""modules.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17V0Foe64DTVofoksinpRGc3Zh2RemAym
"""

import test

test.greetings('Joe')

!pip install seaborn

import seaborn as sns

import seaborn as sns
 
data = [1, 2, 10, 3, 5, 6, 13]

sns.lineplot(x=range(7),y=data)