# -*- coding: utf-8 -*-
"""exception_handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZvN9zDIsAWzeeFCkPUFZaGpRL4JgUyx
"""

def divide(number1, number2):
   number1_integer = int(number1)
   number2_integer = int(number2)
   return number1_integer / number2_integer
 
number1 = input('Please provide number1: ')
number2 = input('Please provide number2: ')
 
print(divide(number1, number2))

def divide(number1, number2):
   try:
       number1_integer = int(number1)
       number2_integer = int(number2)
       return number1_integer / number2_integer
 
   except:
       return 'Only integers are allowed! Try again.'
 
number1 = input('Please provide a number1: ')
number2 = input('Please provide a number2: ')
 
print(divide(number1, number2))

def divide(number1, number2):
   try:
       number1_integer = int(number1)
       number2_integer = int(number2)
       return number1_integer / number2_integer
  
   except ValueError:
       return 'Only integers are allowed!'
 
   except ZeroDivisionError:
       return 'You cannot divide any number by zero!'



number1 = input('Please provide a number1: ')
number2 = input('Please provide a number2: ')
 
print(divide(number1, number2))