# -*- coding: utf-8 -*-
"""file_operations.ipynb

Automatically generated by Colaboratory.

"""

# Commented out IPython magic to ensure Python compatibility.

# %cd /content/file_operations

message_file = open("message.txt")

message_file = open("/content/file_operations/message.txt")

message_file = open("message.txt", "r")

content = message_file.read()
message_file.close()

print(content)

hello_file = open("hello.txt", "w")

hello_file.write('Hello world, this is Python')
hello_file.close()

​​import random
while True:

  random_number = random.randrange(1000)
  print(random_number)
 
  if random_number == 777:
    print('Found!')
    break

import random
 
numbers_file = open('number_history.txt', 'w')
 
while True:
 
  random_number = random.randrange(1000)
  print(random_number)
  numbers_file.write(str(random_number))
  numbers_file.write('\n')
 
  if random_number == 777:
    print('Found!')
    numbers_file.write('Found!')
    numbers_file.close()
    break

import random
 
with open('number_history.txt', 'w') as numbers_file:
 
  while True:

    random_number = random.randrange(1000)
    print(random_number)
    numbers_file.write(str(random_number))
    numbers_file.write('\n')
 
    if random_number == 777:
      print('Found!')
      numbers_file.write('Found!')
      break
