# -*- coding: utf-8 -*-
"""break_infinite_loops.ipynb

Automatically generated by Colaboratory.


while True:
  print('I love you!')

import time
counter = 0
 
while counter >= 0:
  counter += 1
 
  print(counter)
  time.sleep(1)

import random
while True:
 
    random_number = random.randrange(1000)
    print(random_number)
 
    if random_number == 777:
        print('Found!')
        break

names = ['Max', 'Felix', 'Deniz', 'Selin', 'Lucas', 26, 'Sarah']
 
for name in names:
 
    if type(name) != str:
        print('Found', name)
        break
 
    else:
        print(name, 'is a string!')