# -*- coding: utf-8 -*-
"""for_loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a5W4mzjmB4HNQibC2QR7CNxevU9dDclp
"""

print('E')
print('y')
print('j')
print('a')
print('f')
print('j')
print('a')
print('l')
print('l')
print('a')
print('j')
print('ö')
print('k')
print('u')
print('l')
print('l')

volcano_name = 'Eyjafjallajökull'
 
for i in volcano_name:
  print(i)
print('Loop is completed')

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9,10]
for i in numbers:
  print(i)
 
print('Loop is completed')

for i in range(5,21):
  print(i)
print('Loop is completed')

for i in range(1,101):
  if i % 5 == 0:
    print(i)
 
print('Loop has been completed')