# -*- coding: utf-8 -*-
"""while_loops.ipynb

Automatically generated by Colaboratory.


celsius = 10

if celsius > 30:
  print('Hot')
elif 30 >= celsius > 20:
  print('Good ')
elif -273 < celsius <= 20:
  print('Cold ')
else:
  print('Something went wrong!')

celcius = 10
 
while celcius < 50:
 
  if celcius > 30:
    print('Hot ')
  elif 30 >= celcius > 20:
    print('Good ')
  elif -273 < celcius <= 20:              
    print('Cold')
  else:
    print('Something went wrong!')

celcius = 10
 
while celcius < 50:
 
  if celcius > 30:
    print('Hot ')
  elif 30 >= celcius > 20:
    print('Good ')
  elif -273 < celcius <= 20:              
    print('Cold ')
  else:
    print('Something went wrong!')
  celcius += 5

celcius = 10
 
while celcius < 50:
 
  if celcius > 30:
    print('Hot ')
  elif 30 >= celcius > 20:
    print('Good ')
  elif -273 < celcius <= 20:              
    print('Cold ')
  else:
    print('Something went wrong!')
  print('The current temperature is',celcius)
  celcius += 5

import time
celcius = 10
 
while celcius < 50:
 
  if celcius > 30:
    print('Hot ')
  elif 30 >= celcius > 20:
    print('Good ')
  elif -273 < celcius <= 20:              
    print('Cold ')
  else:
    print('Something went wrong!')
  print('The current temperature is',celcius)
  celcius += 5
  time.sleep(1)