# -*- coding: utf-8 -*-
"""import.ipynb

Automatically generated by Colaboratory.


import math

floor_number = (math.floor(3.45))
print(floor_number, type(floor_number))

import datetime

print(datetime.datetime.now())

import random

print(random.randint(1,6))