# -*- coding: utf-8 -*-
"""input_output_functions.ipynb

Automatically generated by Colaboratory.


print("Hi, this is Python")

name = "Joe"
print(name)

name = "Alice"
print('Hello', name)

print(15)

name = input('Name:')
print('Greetings', name)

number = int(input("Number: "))
print(number + 10)