# -*- coding: utf-8 -*-
"""operators.ipynb

Automatically generated by Colaboratory.


print(2 + 5)

print("5 + 2 =", 5+2)
print("5 - 2 =", 5-2)
print("5 * 2 =", 5*2)
print("5 / 2 =", 5/2)
print("5 // 2 =", 5//2)
print("5 ** 2 =", 5**2)
print("5 % 2 =", 5%2)

x = 5 # equivalent to x = 5
x += 5 # equivalent to x = x + 5
x -= 5 # equivalent to x = x - 5
x *= 5 # equivalent to x = x * 5
x /= 5 # equivalent to x = x / 5
x %= 5 # equivalent to x = x % 5
x //= 5 # equivalent to x = x // 5
x **= 5 # equivalent to x = x ** 5

num1 = 10
num2 = 5

print(num1, ">", num2, "=", num1 > num2)
print(num1, ">=", num2, "=", num1 >= num2)
print(num1, "<", num2, "=", num1 < num2)
print(num1, "<=", num2, "=", num1 <= num2)
print(num1, "==", num2, "=", num1 == num2)
print(num1, "!=", num2, "=", num1 != num2)

print("True and True =", True and True)
print("True and False =", True and False)
print("False and True =", False and True)
print("False and False =", False and False)

print(True and False and False)

print("True or True =", True or True)
print("True or False =", True or False)
print("False or True =", False or True)
print("False or False =", False or False)

print("not True =", not True)
print("not False =", not False)