# -*- coding: utf-8 -*-
"""statements_and_comments.ipynb

Automatically generated by Colaboratory.


pi = 3.14

print(pi)

def greetings(name):
    print(f'Hello, {name}')

pi = 3.14
if pi < 3.15:
  pi = pi + 0.1

print(pi)

#This function shows a greeting message according to the given name
def greetings(name):
    print(f'Hello, {name}')

def greeting(name):
  print('hello ' + name)
greeting('Joe')
#greeting('Joe')

def greetings(name):
    print(f'Hello, {name}')
greetings('Joe')