# -*- coding: utf-8 -*-
"""dictionaries.ipynb

Automatically generated by Colaboratory.


phone_book = {'Joe Smith':'+90 505 123 45 67', 'Ellen Olsen': '+49 157 12345678', 'Wendy Adams':'+1 234 235 5678'}
print(phone_book)

print(phone_book['Joe Smith'])

inventory = dict()
inventory['bananas'] = 25
inventory['apples'] = 102
inventory['oranges'] = 54
inventory['watermelons'] = 4

print(inventory)

print(inventory['apples'])

print(inventory.keys())

print(inventory.values())

print(inventory.items())

for element in inventory:
  print(element)

for key in inventory:
  inventory[key] += 100
 
print(inventory)

for key, value in inventory.items():
    if value > 200:
        print('Too many', key)
    else:
        print('Enough', key)